### ISSUE TITLE
Connection tab won't display after selecting a serial connection

### ISSUE THREAD

**Issue by lephino** [futzle/MiOS-CaddxNX584#1]
All occurrences of "jsonp.get_lu_device_variable_value" need to be changed to "get_device_state".

Lines 142-153 are the main culprits of J_CaddxNX584SerialConnection.js.

**Comment by futzle** [comment]
You're right, I must have missed these ones because I don't use a direct serial connection.  Have you got a pull request for me?  Or at least a patch?

**Comment by lephino** [comment]
Added a pull request for it.

**Comment by futzle** [comment]
Fixed by #2
